"""Base classes and interfaces for Tool system.

This module provides the core abstractions for the tool system,
including the Tool interface and ToolResult dataclass.

Example:
    >>> from nergal.tools.base import Tool, ToolResult
    >>>
    >>> class EchoTool(Tool):
    ...     @property
    ...     def name(self) -> str:
    ...         return "echo"
    ...
    ...     @property
    ...     def description(self) -> str:
    ...         return "Echo the input"
    ...
    ...     @property
    ...     def parameters_schema(self) -> dict:
    ...         return {
    ...             "type": "object",
    ...             "properties": {
    ...                 "text": {"type": "string"}
    ...             }
    ...         }
    ...
    ...     async def execute(self, args: dict) -> ToolResult:
    ...         return ToolResult(
    ...             success=True,
    ...             output=args.get("text", "")
    ...         )
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ToolResult:
    """Result of tool execution.

    Represents the outcome of executing a tool, including
    success status, output, and optional error information.

    Attributes:
        success: Whether the tool execution succeeded.
        output: The output generated by the tool (can be empty string).
        error: Optional error message if execution failed.
        metadata: Optional metadata about execution (timing, attempts, etc.).

    Examples:
        Successful result:
        >>> result = ToolResult(success=True, output="File written")

        Error result:
        >>> result = ToolResult(
        ...     success=False,
        ...     output="",
        ...     error="Permission denied"
        ... )

        Result with metadata:
        >>> result = ToolResult(
        ...     success=True,
        ...     output="Done",
        ...     metadata={"execution_time": 0.5}
        ... )
    """

    success: bool
    """Whether the tool execution succeeded."""

    output: str
    """The output generated by the tool (can be empty string)."""

    error: str | None = field(default=None)
    """Optional error message if execution failed."""

    metadata: dict[str, Any] | None = field(default=None)
    """Optional metadata about execution (timing, attempts, etc.)."""


class Tool(ABC):
    """Abstract base class for all tools.

    All tools in the system must inherit from this class and implement
    the required abstract methods and properties.

    A tool represents a capability that the agent can use, such as
    reading files, executing shell commands, making HTTP requests, etc.

    Required properties:
        - name: Unique identifier for the tool
        - description: Human-readable description for the LLM
        - parameters_schema: JSON Schema for tool parameters

    Required method:
        - execute: Async method to execute the tool with given arguments

    Example:
        >>> class ReadFileTool(Tool):
        ...     def __init__(self, workspace_dir: str):
        ...         self.workspace_dir = workspace_dir
        ...
        ...     @property
        ...     def name(self) -> str:
        ...         return "file_read"
        ...
        ...     @property
        ...     def description(self) -> str:
        ...         return "Read a file from the workspace"
        ...
        ...     @property
        ...     def parameters_schema(self) -> dict:
        ...         return {
        ...             "type": "object",
        ...             "properties": {
        ...                 "path": {
        ...                     "type": "string",
        ...                     "description": "Path to the file"
        ...                 }
        ...             }
        ...         }
        ...
        ...     async def execute(self, args: dict) -> ToolResult:
        ...         path = args.get("path", "")
        ...         try:
        ...             with open(path, "r") as f:
        ...                 content = f.read()
        ...             return ToolResult(success=True, output=content)
        ...         except Exception as e:
        ...             return ToolResult(
        ...                 success=False,
        ...                 error=str(e)
        ...             )
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique tool identifier.

        This should be a snake_case string that uniquely identifies
        the tool. It will be used by the LLM to select
        the appropriate tool.

        Returns:
            Unique tool identifier (e.g., "file_read", "shell_execute").

        Examples:
            >>> tool.name
            'file_read'
        """
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Human-readable description for the LLM.

        This description should clearly explain what the tool does
        and when to use it. The LLM uses this information
        to decide when to call the tool.

        Returns:
            Human-readable description (e.g., "Read a file from the workspace").

        Examples:
            >>> tool.description
            'Read a file from the workspace'
        """
        pass

    @property
    @abstractmethod
    def parameters_schema(self) -> dict[str, Any]:
        """JSON Schema for tool parameters.

        This schema describes the parameters that the tool accepts.
        It will be sent to the LLM to help it generate
        valid tool calls.

        The schema should follow JSON Schema draft 7 format.

        Returns:
            JSON Schema object describing tool parameters.

        Examples:
            >>> tool.parameters_schema
            {
                'type': 'object',
                'properties': {
                    'path': {
                        'type': 'string',
                        'description': 'Path to the file'
                    }
                },
                'required': ['path']
            }
        """
        pass

    @abstractmethod
    async def execute(self, args: dict[str, Any]) -> ToolResult:
        """Execute the tool with given arguments.

        This is the main method that performs the tool's action.
        It receives the arguments parsed from the LLM's tool call
        and should return a ToolResult indicating success or failure.

        Args:
            args: Dictionary of arguments from the LLM tool call.
                    The keys and values match the parameters_schema.

        Returns:
            ToolResult containing:
                - success: Whether execution succeeded
                - output: The tool's output (can be empty)
                - error: Error message if failed (optional)
                - metadata: Additional execution metadata (optional)

        Examples:
            >>> result = await tool.execute({"path": "/tmp/file.txt"})
            >>> result.success
            True
            >>> result.output
            'File content here...'
        """
        pass
